### ISSUE TITLE
Quickstart guide?

### ISSUE THREAD

**Issue by mrbluecoat** [ncsa/http-logger#1]
Is this still active? Any guide for using a public RPZ list, like https://hblock.molinero.dev/hosts_rpz.txt

**Comment by JustinAzoff** [comment]
Hi,

Not super active.. but not much work is required since it really only does one thing and doesn't have any known issues.

I just added a go.mod file so new versions of go will build it. This is really all there is to it:

```
$ git clone https://github.com/ncsa/http-logger
Cloning into 'http-logger'...
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 86 (delta 0), reused 2 (delta 0), pack-reused 83
Receiving objects: 100% (86/86), 12.41 KiB | 977.00 KiB/s, done.
Resolving deltas: 100% (35/35), done.

$ cd http-logger/
$ go build
$ ./http-logger 
Listening for HTTPS on :8443
Listening for HTTP  on :8080
open cert.pem: no such file or directory
```

at that point it'll fully log any request it receives.  You can use iptables to redirect all the ports you care about to port 8080 and 8443.  For a real deployment the Makefile uses fpm to build an rpm that auto sets up the service and all that fun stuff.

It doesn't do the actual rpz bits, instead you can use this server as the destination for any host you block USING rpz.  That way if you block evil.example.com using rpz, instead of responding with NXDOMAIN or with 127.0.0.1, you redirect it to a server running http-logger, then you have the http-logger output go into your SIEM.  Then in the SIEM you can see what things are trying to be sent to the site that you blocked.

So hope that helps.. I think you might be looking for another type of project that actually implements the rpz process, but this might still be useful to you in the future.
